services:
  investlens.gateway:
    image: ${DOCKER_REGISTRY-}investlensgateway
    container_name: investlens_gateway
    environment:
     - DATA_BASE_ADDRESS=https://investlens_data_api:8081
    build:
      context: .
      dockerfile: src/InvestLens.Gateway/Dockerfile

  investlens.web:
    image: ${DOCKER_REGISTRY-}investlensweb
    container_name: investlens_web
    env_file: 
      - src/InvestLens.Web/.env
    environment:
      - DB_HOST=investlens_postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=investlens_redis
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_HOST=investlens_rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    build:
      context: .
      dockerfile: src/InvestLens.Web/Dockerfile
    depends_on:
      investlens.data.api:
        condition: service_healthy

  investlens.data.api:
    image: ${DOCKER_REGISTRY-}investlensdataapi
    container_name: investlens_data_api
    env_file: 
      - src/InvestLens.Data/InvestLens.Data.Api/.env
    environment:
      - DB_HOST=investlens_postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=investlens_redis
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_HOST=investlens_rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    build:
      context: .
      dockerfile: src/InvestLens.Data/InvestLens.Data.Api/Dockerfile
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/health"]  # если есть health endpoint
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s
    depends_on:
      investlens.postgres:
        condition: service_healthy
      investlens.redis:
        condition: service_healthy
      investlens.rabbitmq:
        condition: service_healthy

  investlens.worker:
    image: ${DOCKER_REGISTRY-}investlensworker
    container_name: investlens_worker
    env_file: 
      - src/InvestLens.Worker/.env
    environment:
      - DB_HOST=investlens_postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=investlens_redis
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_HOST=investlens_rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    build:
      context: .
      dockerfile: src/InvestLens.Worker/Dockerfile
    depends_on:
      investlens.postgres:
        condition: service_healthy
      investlens.redis:
        condition: service_healthy
      investlens.rabbitmq:
        condition: service_healthy

  investlens.telegrambot:
    image: ${DOCKER_REGISTRY-}investlenstelegrambot
    container_name: investlens_telegrambot
    env_file: 
      - src/InvestLens.TelegramBot/.env
    environment:
      - REDIS_HOST=investlens_redis
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_HOST=investlens_rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    build:
      context: .
      dockerfile: src/InvestLens.TelegramBot/Dockerfile
    depends_on:
      investlens.redis:
        condition: service_healthy
      investlens.rabbitmq:
        condition: service_healthy

  investlens.postgres:
    image: postgres:15-alpine
    container_name: investlens_postgres
    env_file:
      - .env
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 10s

  investlens.redis:
    image: redis:7-alpine
    container_name: investlens_redis
    env_file:
      - .env
    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 3s
        retries: 5
    restart: unless-stopped

  investlens.rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: investlens_rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-rabbitmq}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-rabbitmq}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-/}
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 5
    restart: unless-stopped

  investlens.prometheus:
    image: prom/prometheus:latest
    container_name: investlens_prometheus
    restart: unless-stopped

  investlens.grafana:
    image: grafana/grafana:latest
    container_name: investlens_grafana
    depends_on:
      - investlens.prometheus
    restart: unless-stopped