global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus сам мониторит себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  # ASP.NET Core Web-клиент
  - job_name: 'web-client'
    static_configs:
      - targets: ['investlens_web:8080']
    metrics_path: '/metrics'
  
  # Gateway (YARP)
  - job_name: 'gateway'
    static_configs:
      - targets: ['investlens_gateway:8080']
    metrics_path: '/metrics'
  
  # Data Service
  - job_name: 'data-service'
    static_configs:
      - targets: ['investlens_data_api:8080']
    metrics_path: '/metrics'